name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
      
  test:
  
    runs-on: ubuntu-latest
    
    steps:
    - name: Diesel CLI - database setup
      uses: kenaniah/diesel-cli-action@v1
      with: 
        command:
          setup
          migration run
          test --verbose -- --include-ignored
      env:
        WORKING_DIRECTORIES: ./migrations/
