name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
      
  diesel:
  
    runs-on: ubuntu-latest
    
    steps:
    - name: install diesel-rs
      run: |
           sudo apt-get install libsqlite3-dev
           cargo install diesel_cli --no-default-features --features sqlite
    - name: Checkout
      uses: actions/checkout@v3
    - name: Diesel CLI - database setup
      run: |     
           diesel setup
           diesel migration run 
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: run tests
      run: |
        cargo test --verbose -- --include-ignored update
        cargo test --verbose -- --include-ignored fill
        cargo test --verbose
      env:
        WORKING_DIRECTORIES: ./migrations/
