name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
      
  test:
  
    runs-on: ubuntu-latest
    
    steps:
    - uses: ducharmemp/diesel-cli-action@0.1.0
    - name: Setup Database
      run: diesel setup
           diesel migration run
           cargo test --verbose -- --include-ignored        
